### PR TITLE
Use the new flat logo

### PR DESCRIPTION
**Pull request by enthuan**
The logo is changed to match the one on the https://androidmakers.droidcon.com website.

Capture d’écran 2024-03-27 à 17 56 16
Capture d’écran 2024-03-27 à 17 56 02

I also adapted the @BapNesS monochrome icon to notification format on Android

### CODE REVIEW

**Review by martinbonnin — APPROVED** [review]

**Comment by benju69** [comment]
hmm the "flat" logo is wrong actually, it's just a bugged svg with no shadows, can you keep the old logo?

**Comment by enthuan** [comment]
Oh ok ! I thought it was on purpose, I revert it to the previous version sorryAntoine RobiezLe 27 mars 2024 à 19:54, Benjamin Gonin ***@***.***> a écrit :﻿
hmm the "flat" logo is wrong actually, it's just a bugged svg with no shadows, can you keep the old logo?

**Comment by enthuan** [comment]
Should I just add shadows on this one ? Because I think the colors are slightly different but I may be wrong.

**Comment by enthuan** [comment]
I checked and the colors are actually the same. I just rollback the app icons and add shadows on the "by Droidcon" logo

**Pull request merged**
