### PR TITLE
UI Redesign

### PR DESCRIPTION
**Pull request by renaudmathieu**
- App redesign
- Add Speaker details screen
Screenshot_20230419_112938
Screenshot_20230419_112947

### CODE REVIEW

**Comment by martinbonnin** [comment]
Niiiiice 🤩

**Comment by martinbonnin** [comment]
One small comment: looks like the top app bar is now taking more vertical space? Could we make everything fit on 1 line?

**Comment by renaudmathieu** [comment]
Afraid that small devices will only see "Android Makers by droid…". That's the only reason I switched to a MediumTopAppBar. WDYT?

**Comment by martinbonnin** [comment]
I'm team "dense" so I prefer the smaller app bar but this goes into personal preference land. Feel free to merge 👍

**Review by martinbonnin — APPROVED** [review]

**Comment by renaudmathieu** [comment]
this logo won't work in dark theme I think

**Pull request merged**
